In [1]:
import pandas as pd
from scipy.stats import linregress
import matplotlib.pyplot as plt

In [74]:
# functions to project values based off current rate of increase 
def forecast_var(x,y):
    forecast_y=[]
    future_x=[]
    x=x[-20:]
    y=y[-20:]
    slope, intercept, rvalue, pvalue, stderr= linregress(x,y)
    start_x=x[-1]
    start_y=y[-1]
    for j in range(2201-start_x):
        j+=1
        new_x=start_x+j
        new_y=slope*(new_x)+intercept
        forecast_y.append(new_y)
        future_x.append(new_x)
    return(future_x, forecast_y)

def forecast_df(df):
    columns=df.columns.to_list()
    proj_df=pd.DataFrame(columns=columns)
    for j in columns:
        if (j=='Year'):
            x=df.Year.to_list()
        else:
            y=df[f'{j}'].to_list()
            future_x, forecast_y=forecast_var(x,y)
            proj_df[f'{j}']=forecast_y
            proj_df['Year']=future_x
    return proj_df

def forecast_change(x,y):
    forecast_y=[]
    future_x=[]
    x=x[-20:]
    y=y[-20:]
    slope, intercept, rvalue, pvalue, stderr= linregress(x,y)
    start_x=x[-1]
    start_y=y[-1]
    for j in range(2201-start_x):
        j+=1
        slope=slope*1.0005
        print(slope)
        new_x=start_x+j
        new_y=slope*(new_x)+intercept
        forecast_y.append(new_y)
        future_x.append(new_x)
    return(future_x, forecast_y)

In [3]:
data=pd.read_csv('Resources/model_3.csv')

In [4]:
del data['Unnamed: 0']
del data['Total']
del data['Per Capita']

In [6]:
data=data.drop(columns=['concentration'])
data

     Year  Gas Fuel  Liquid Fuel  Solid Fuel  Cement  Gas Flaring
0    1752         0            0           3       0            0
1    1763         0            0           3       0            0
2    1764         0            0           3       0            0
3    1773         0            0           4       0            0
4    1779         0            0           4       0            0
..    ...       ...          ...         ...     ...          ...
136  2006      1525         3089        3339     356           61
137  2007      1572         3081        3464     382           68
138  2008      1631         3122        3571     388           71
139  2009      1585         3056        3620     413           66
140  2010      1702         3114        3842     450           59

[141 rows x 6 columns]

In [7]:
noChangeProjections=forecast_df(data)
noChangeProjections

     Year     Gas Fuel   Liquid Fuel    Solid Fuel       Cement  Gas Flaring
0    2011  1676.152632   3214.210526   3609.568421   418.336842    66.994737
1    2012  1708.262406   3250.635338   3688.622556   432.830827    68.818045
2    2013  1740.372180   3287.060150   3767.676692   447.324812    70.641353
3    2014  1772.481955   3323.484962   3846.730827   461.818797    72.464662
4    2015  1804.591729   3359.909774   3925.784962   476.312782    74.287970
..    ...          ...           ...           ...          ...          ...
186  2197  7648.570677   9989.225564  18313.637594  3114.218045   406.130075
187  2198  7680.680451  10025.650376  18392.691729  3128.712030   407.953383
188  2199  7712.790226  10062.075188  18471.745865  3143.206015   409.776692
189  2200  7744.900000  10098.500000  18550.800000  3157.700000   411.600000
190  2201  7777.009774  10134.924812  18629.854135  3172.193985   413.423308

[191 rows x 6 columns]

In [8]:
# noChangeProjections.to_csv('Resources/MasterProjected.csv')

In [95]:
x=data['Year'].to_list()
y=data['Gas Flaring'].to_list()

In [96]:
future_x, forecast_y=forecast_change(x,y)

1.8242199248120299
1.8251320347744358
1.826044600791823
1.8269576230922189
1.8278711019037648
1.8287850374547165
1.8296994299734437
1.8306142796884304
1.8315295868282746
1.8324453516216885
1.8333615742974994
1.834278255084648
1.8351953942121901
1.8361129919092962
1.8370310484052508
1.8379495639294534
1.838868538711418
1.8397879729807738
1.840707866967264
1.8416282209007475
1.8425490350111977
1.8434703095287033
1.8443920446834676
1.8453142407058092
1.846236897826162
1.847160016275075
1.8480835962832125
1.849007638081354
1.8499321419003947
1.8508571079713447
1.8517825365253302
1.8527084277935928
1.8536347820074894
1.8545615993984932
1.8554888801981924
1.8564166246382914
1.8573448329506104
1.8582735053670856
1.859202642119769
1.8601322434408287
1.8610623095625491
1.8619928407173303
1.8629238371376888
1.8638552990562576
1.8647872267057857
1.8657196203191384
1.8666524801292979
1.8675858063693624
1.868519599272547
1.8694538590721832
1.870388586001719
1.8713237802947198
1.872259442184867
1.8731955719059594
1.8741321696919122
1.875069235776758
1.8760067703946464
1.8769447737798435
1.8778832461667332
1.8788221877898164
1.879761598883711
1.880701479683153
1.8816418304229945
1.8825826513382058
1.8835239426638748
1.8844657046352067
1.885407937487524
1.8863506414562679
1.887293816776996
1.8882374636853843
1.889181582417227
1.8901261732084353
1.8910712362950395
1.8920167719131868
1.8929627802991433
1.8939092616892927
1.8948562163201372
1.8958036444282973
1.8967515462505113
1.8976999220236366
1.8986487719846483
1.8995980963706405
1.9005478954188257
1.9014981693665352
1.9024489184512183
1.903400142910444
1.904351842981899
1.9053040189033899
1.9062566709128415
1.9072097992482977
1.9081634041479218
1.9091174858499957
1.9100720445929207
1.911027080615217
1.9119825941555244
1.912938585452602
1.9138950547453282
1.9148520022727007
1.915809428273837
1.9167673329879737
1.9177257166544677
1.9186845795127947
1.919643921802551
1.9206037437634522
1.9215640456353338
1.9225248276581512
1.9234860900719801
1.924447833117016
1.9254100570335744
1.926372762062091
1.9273359484431218
1.9282996164173434
1.9292637662255518
1.9302283981086645
1.9311935123077189
1.9321591090638726
1.9331251886184044
1.9340917512127136
1.9350587970883197
1.9360263264868638
1.936994339650107
1.937962836819932
1.938931818238342
1.939901284147461
1.9408712347895347
1.9418416704069295
1.9428125912421328
1.9437839975377538
1.9447558895365225
1.9457282674812906
1.946701131615031
1.9476744821808385
1.9486483194219288
1.9496226435816397
1.9505974549034304
1.951572753630882
1.9525485400076974
1.953524814277701
1.95450157668484
1.9554788274731822
1.9564565668869187
1.9574347951703621
1.9584135125679472
1.959392719324231
1.960372415683893
1.9613526018917349
1.9623332781926806
1.9633144448317768
1.9642961020541925
1.9652782501052195
1.966260889230272
1.967244019674887
1.9682276416847244
1.9692117555055666
1.9701963613833193
1.971181459564011
1.972167050293793
1.9731531338189396
1.974139710385849
1.9751267802410417
1.9761143436311621
1.9771024008029776
1.978090952003379
1.9790799974793805
1.98006953747812
1.9810595722468591
1.9820501020329824
1.9830411270839987
1.9840326476475405
1.9850246639713642
1.9860171763033498
1.9870101848915014
1.988003689983947
1.988997691828939
1.9899921906748532
1.9909871867701905
1.9919826803635754
1.992978671703757
1.9939751610396088
1.9949721486201286
1.9959696346944387
1.9969676195117858
1.9979661033215417
1.9989650863732022
1.9999645689163887
2.000964551200847
2.001965033476447
2.0029660159931852
2.0039674990011815
2.004969482750682
2.0059719674920573

In [98]:
fifth_change['Gas Flaring']=forecast_y

In [100]:
# fifth_change.to_csv('Resources/master_OneFifth_increase.csv')