In [3]:
import requests
import pandas as pd
import json
import csv

In [5]:
dataTypes_df = pd.read_csv("NOAA_filtDatatypes.csv")
dataTypes_df

,mindate,maxdate,name,datacoverage,id
0,1763-01-01,2020-09-01,Cooling Degree Days Season to Date,1.0,CDSD
1,1763-01-01,2020-09-01,Cooling Degree Days,1.0,CLDD
2,1832-05-11,2020-10-22,Number of days included in the multiday precip...,1.0,DAPR
3,1863-05-04,2020-10-22,Number of days included in the multiday minimu...,1.0,DATN
4,1863-05-04,2020-10-21,Number of days included in the multiday maximu...,1.0,DATX
...,...,...,...,...,...
68,1852-02-12,2020-10-16,Blowing or drifting snow,1.0,WT09
69,1851-04-03,2020-09-30,High or damaging winds,1.0,WT11
70,1851-09-06,2018-06-19,Drizzle,1.0,WT14
71,1851-04-01,2019-07-30,"Rain (may include freezing rain, drizzle, and ...",1.0,WT16
72,1851-04-13,2019-04-13,"Snow, snow pellets, snow grains, or ice crystals",1.0,WT18

In [6]:
dataTypes_df = dataTypes_df.drop([0,1,2,3,4,5,6,8,10,11,13,14,15,17,18,19,20,21,27,28,29,30,31,32,33,34,35,36,37,40,45,46,47,48,59,62,63,64,65,66,67,68,69,70,71,72])

In [7]:
dataTypes_df

,mindate,maxdate,name,datacoverage,id
7,1781-01-01,2020-09-01,Number of days with greater than or equal to 1...,1.0,DP10
9,1840-05-01,2020-09-01,Number days with snow depth > 1 inch.,1.0,DSNW
12,1763-01-01,2016-03-01,Number days with maximum temperature greater t...,1.0,DT90
16,1763-01-01,2020-09-01,Number days with maximum temperature > 90 F (3...,1.0,DX90
22,1763-01-01,2020-09-01,Extreme minimum temperature for the period.,1.0,EMNT
23,1863-12-01,2020-09-01,Extreme maximum snow depth for the period.,1.0,EMSD
24,1840-05-01,2020-09-01,Extreme maximum snowfall for the period.,1.0,EMSN
25,1781-01-01,2020-09-01,Extreme maximum precipitation for the period.,1.0,EMXP
26,1763-01-01,2020-09-01,Extreme maximum temperature for the period.,1.0,EMXT
38,1781-01-04,2020-10-22,Precipitation,1.0,HPCP
39,1840-10-24,2020-10-22,Highest snowfall,NaN,HSNW
41,1763-01-01,2020-10-22,Highest minimum temperature,NaN,HTMN
42,1763-01-01,2020-10-22,Highest maximum temperature,NaN,HTMX
43,1763-01-01,2020-10-22,Lowest minimum temperature,NaN,LTMN
44,1763-01-01,2020-10-22,Lowest maximum temperature,NaN,LTMX
49,1763-01-01,2016-03-01,Monthly Mean minimum temperature,1.0,MMNT
50,1763-01-01,2016-03-01,Monthly Mean maximum temperature,1.0,MMXT
51,1763-01-01,2016-03-01,Monthly mean temperature,1.0,MNTM
52,1857-01-01,2016-03-01,Maximum snow depth,1.0,MXSD
53,1781-01-01,2020-10-22,Precipitation,1.0,PRCP
54,1840-05-01,2020-10-22,Snowfall,1.0,SNOW
55,1857-01-18,2020-10-22,Snow depth,1.0,SNWD
56,1763-01-01,2020-10-22,Average Temperature.,1.0,TAVG
57,1763-01-01,2020-10-22,Maximum temperature,1.0,TMAX
58,1763-01-01,2020-10-22,Minimum temperature,1.0,TMIN
60,1781-01-01,2016-03-01,Total precipitation,1.0,TPCP
61,1840-05-01,2016-03-01,Total snow fall,1.0,TSNW