In [1]:
import requests
import pandas as pd
import json
from config import NOAA_token

In [2]:
url = "https://www.ncdc.noaa.gov/cdo-web/api/v2/datatypes"
data = {
    "limit": 1000
}
headers = {"token": NOAA_token}

response = requests.get(url, params=data, headers=headers)
response_json = response.json()
datatypes = pd.json_normalize(response_json["results"])
datatypes

,mindate,maxdate,name,datacoverage,id
0,1994-03-19,1996-05-28,Average cloudiness midnight to midnight from 3...,1.00,ACMC
1,1965-01-01,2005-12-31,Average cloudiness midnight to midnight from m...,1.00,ACMH
2,1994-02-01,1996-05-28,Average cloudiness sunrise to sunset from 30-s...,1.00,ACSC
3,1965-01-01,2005-12-31,Average cloudiness sunrise to sunset from manu...,1.00,ACSH
4,1991-06-05,2020-10-21,Base Data,0.95,ALL
...,...,...,...,...,...
995,2010-01-01,2010-12-01,Long-term averages of monthly cooling degree d...,1.00,MLY-CLDD-NORMAL
996,2010-01-01,2010-12-01,Long-term averages of monthly diurnal temperat...,1.00,MLY-DUTR-NORMAL
997,2010-01-01,2010-12-01,Long-term standard deviations of monthly diurn...,1.00,MLY-DUTR-STDDEV
998,2010-01-01,2010-12-01,Long-term averages of monthly growing degree d...,1.00,MLY-GRDD-BASE40
999,2010-01-01,2010-12-01,Long-term averages of monthly growing degree d...,1.00,MLY-GRDD-BASE45

In [4]:
url = "https://www.ncdc.noaa.gov/cdo-web/api/v2/datatypes"
data = {
    "limit": 1000,
    "offset":1000
}
headers = {"token": NOAA_token}

response = requests.get(url, params=data, headers=headers)
response_json = response.json()
datatypes2 = pd.json_normalize(response_json["results"])
datatypes = datatypes.append(datatypes2)
datatypes

,mindate,maxdate,name,datacoverage,id
0,1994-03-19,1996-05-28,Average cloudiness midnight to midnight from 3...,1.00,ACMC
1,1965-01-01,2005-12-31,Average cloudiness midnight to midnight from m...,1.00,ACMH
2,1994-02-01,1996-05-28,Average cloudiness sunrise to sunset from 30-s...,1.00,ACSC
3,1965-01-01,2005-12-31,Average cloudiness sunrise to sunset from manu...,1.00,ACSH
4,1991-06-05,2020-10-21,Base Data,0.95,ALL
...,...,...,...,...,...
531,1996-07-08,2005-09-09,"Ash, dust, sand, or other blowing obstruction",1.00,WV07
532,1996-10-21,2002-02-04,Snow or ice crystals,1.00,WV18
533,1996-07-01,2005-12-31,Rain or snow shower,1.00,WV20
534,2010-01-01,2010-12-31,Long-term average year-to-date precipitation t...,1.00,YTD-PRCP-NORMAL
535,2010-01-01,2010-12-31,Long-term average year-to-date snowfall totals,1.00,YTD-SNOW-NORMAL

In [5]:
datatypes['mindate'] = pd.to_datetime(datatypes['mindate'])
datatypes['maxdate'] = pd.to_datetime(datatypes['maxdate'])

In [6]:
filtDatatypes = datatypes.loc[(datatypes["mindate"] <= "1880-01-01") & (datatypes["maxdate"] >= "2010-01-01")]
filtDatatypes

,mindate,maxdate,name,datacoverage,id
235,1763-01-01,2020-09-01,Cooling Degree Days Season to Date,1.0,CDSD
236,1763-01-01,2020-09-01,Cooling Degree Days,1.0,CLDD
239,1832-05-11,2020-10-22,Number of days included in the multiday precip...,1.0,DAPR
241,1863-05-04,2020-10-22,Number of days included in the multiday minimu...,1.0,DATN
242,1863-05-04,2020-10-21,Number of days included in the multiday maximu...,1.0,DATX
...,...,...,...,...,...
516,1852-02-12,2020-10-16,Blowing or drifting snow,1.0,WT09
518,1851-04-03,2020-09-30,High or damaging winds,1.0,WT11
521,1851-09-06,2018-06-19,Drizzle,1.0,WT14
523,1851-04-01,2019-07-30,"Rain (may include freezing rain, drizzle, and ...",1.0,WT16
525,1851-04-13,2019-04-13,"Snow, snow pellets, snow grains, or ice crystals",1.0,WT18

In [14]:
for row in filtDatatypes["name"]:
    print(row)

Cooling Degree Days Season to Date
Cooling Degree Days
Number of days included in the multiday precipitation total (MDPR)
Number of days included in the multiday minimum temperature (MDTN)
Number of days included in the multiday maximum temperature (MDTX)
Number of days with greater than or equal to 0.1 inch of precipitation
Number of days with greater than or equal to 0.5 inch of precipitation
Number of days with greater than or equal to 1.0 inch of precipitation
Number days with snow depth > 1 inch(25.4mm) for the period.
Number days with snow depth > 1 inch.
Number days with minimum temperature less than or equal to 0.0 F
Number days with minimum temperature less than or equal to 32.0 F
Number days with maximum temperature greater than or equal 90.0 F
Number of days with non-zero precipitation included in multiday precipitation total (MDPR)
Number days with maximum temperature < 32 F.
Number days with maximum temperature > 70 F (21.1C)
Number days with maximum temperature > 90 F (32.2C)
Day Extreme minimum temperature occurred for the period.
Day the extreme maximum daily Snow Depth for the period occurred.
Day the extreme maximum daily snowfall for the period occurred.
Day Extreme maximum daily precipitation for the period.
Date Extreme maximum temperature occurred for the period.
Extreme minimum temperature for the period.
Extreme maximum snow depth for the period.
Extreme maximum snowfall for the period.
Extreme maximum precipitation for the period.
Extreme maximum temperature for the period.
First freeze <= to 32F/0C of the year.
First freeze <= 28F/-2.2C of the year
First freeze <= 24F/-4.4C of the year
First freeze <= 20F/-6.7C of the year
First freeze <= 16F/-8.9C of the year
Last freeze <= 32F/0C of the year
Last freeze <= 28F/-2.2C of the year
Last freeze <= 24F/-4.4C of the year
Last freeze <= 20F/-6.7C of the year
Last freeze <= 16F/-8.9C of the year
Heating Degree Days Season to Date
Precipitation
Highest snowfall
Heating degree days
Highest minimum temperature
Highest maximum temperature
Lowest minimum temperature
Lowest maximum temperature
Multiday precipitation total (use with DAPR and DWPR, if available)
Multiday snowfall total
Multiday minimum temperature (use with DATN)
Multiday maximum temperature (use with DATX)
Monthly Mean minimum temperature
Monthly Mean maximum temperature
Monthly mean temperature
Maximum snow depth
Precipitation
Snowfall
Snow depth
Average Temperature.
Maximum temperature
Minimum temperature
Temperature at the time of observation
Total precipitation
Total snow fall
Total wind movement
Fog, ice fog, or freezing fog (may include heavy fog)
Thunder
Ice pellets, sleet, snow pellets, or small hail"
Hail (may include small hail)
Smoke or haze
Blowing or drifting snow
High or damaging winds
Drizzle
Rain (may include freezing rain, drizzle, and freezing drizzle)"
Snow, snow pellets, snow grains, or ice crystals

In [15]:
filtDatatypes.to_csv("static/data/NOAA_filtDatatypes.csv", index=False)